rdkcentral/rbus

src/core/rbuscore_message.c
src/rbus/rbus.c
unittests/rbus/rbusApiNegTest.cpp
unittests/rbus/rbusSessionTest.cpp

Reason for change: Fixed memory leaks in session manager code
Test Procedure: Build and test rbus, run valgrind
Risks: Low
Priority: P2

Free the memory leaks from rbus gtest - Session & msg

---

src/rbus/rbus.c
src/rbus/rbus_element.c
src/rtmessage/rtConnection.c
unittests/rbus/rbusApiNegTest.cpp
unittests/rbus/rbusElementTest.cpp
unittests/rbus/rbusObjectTest.cpp
unittests/rbus/rbusPropertyTest.cpp
unittests/rbus/rbusProvider.cpp
unittests/rbus/rbusValueTest.cpp

Reason for change: Gtest Suits listed in Jira RDKB-44513 Description were failing
Test Procedure: Build rtmessage, rbuscore and start rtrouted", Build Rbus Gtests with valgrind mentioned in Jira Description
Risks: Low
Priority: P2

RDKB-44513 - Free the memory leaks from rbus gtest

---

CMakeLists.txt

Reason for change: Enable Code Coverage on the Federated RBUS Component
Test Procedure: Execute gtest and code coverage
Risks: Low

Enable Code Coverage on the Federated RBUS Component

---

src/rtmessage/rtRoutingTree.c

RDKB-44839: Order of Table and its childs registraion in RBUS is addressed 
Reason for change: Facing Duplicate entry while a registering table with "Foo.SomeTable.{i}." format.
As per condition get routeList2 if the requested topic ends with "."and it is not matched with routeList2 topics.
Solution: Removed condition check and returned route list instead of routeList2.
Test Procedure: 1. Run test using rbusTestProvider, rbusTestConsumer
2. check Onewifi CSI feature broken issue.
Risks: Low
Signed-off-by: Netaji <NETAJI_PANIGRAHI@comcast.com>

Order of Table and its childs registraion in RBUS is addressed

---

unittests/rbus_unit_stresstest_server.cpp

Reason for change: While executing rbus_gtest.bin, Getting core_dump error 
Test Procedure: Run rbus_gtest.bin to execute both core and rbus unittests
Risks: Low

Combine rbus and rbuscore Unittest Programs under one single binary

---

src/rbus/rbus.c
unittests/rbusConsumer.cpp

Reason for change: rectified incorrect initialization of structure rbusDateTime_t Test Procedure: Build rtmessage, rbuscore and start rtrouted", Build Rbus Gtests with valgrind mentioned in Jira Description Risks: Low
Priority: P2

Free the memory leaks definitely lost from rbus gtest

---

src/core/rbuscore.c
src/rbus/rbus.c

Reason for change: rbusMethodConsumer and rbusMethodProvider crashing Test Procedure: Run rbusMethodProvider and run rbusMethodConsumer with valgrind
Risks: Low
Signed-off-by: Deepthi <DEEPTHICHANDRASHEKAR_SHETTY@comcast.com>

RDKB-45363: RBUS Sample App (rbusMethodConsumer) crashing

---

src/rbus/rbus.c
src/rtmessage/rtRoutingTree.c
src/rtmessage/rtRoutingTree.h
src/rtmessage/rtrouted.c

Reason for change: Made changes to discover all the components owner for the wild card query and send notification only to the data model registered component in case of addition and deletion of property/table
Risks: Medium
Priority: P0

RDKB-45652: Can't find destination component for multiple parameters

---

include/rbus.h
src/core/rbuscore.c
src/rbus/rbus.c
src/rbus/rbus_tokenchain.c
src/rtmessage/rtConnection.c
unittests/rbusConsumer.cpp
unittests/rbusTokenTest.cpp
unittests/rbus_unit_test_client.cpp
unittests/rbus_unit_test_multiple_servers.cpp

Reason for change: Memory leak in rbus_gtest.bin
Test Procedure: run rbus_gtest.bin with valgrind
Risks: Low
Signed-off-by: Deepthi <DEEPTHICHANDRASHEKAR_SHETTY@comcast.com>

RDKB-45530: Memory leak in rbus_gtest.bin

---

src/core/rbuscore_logger.h
src/rbus/rbus_log.h
src/rtmessage/rtLog.c
src/rtmessage/rtLog.h

RDKB-45280:Update the rtLog to support RDKLogger appropriately and modify rbus and rbuscore to use the rtLog Macro
Reason for change:Update the rtLog to support RDKLogger appropriately and modify rbus and rbuscore to use the rtLog Macro Test Procedure: Tested on VM: Run-rtrouted for RTMESSAGE log (Terminal1), RbusProvider(Term2) and rbuscli or rbusConsumer For RBUS logs(Term3), rbus_session_mgr For RBUSCORE logs(Term4) Risks: Low
Priority: P1

RDKB-45280:Update the rtLog to support RDKLogger appropriately and modify rbus and rbuscore to use the rtLog Macro

---

rdk_build.sh
src/rtmessage/CMakeLists.txt

RDKC-12575:[CI][AUTO] Xw4 Version retrieved are different after CDL - RDKLOGGER is not ON in xCAM2 and xCAM3
Reason for change: Enabled ENABLE_RDKLOGGER=ON in rdk_build.sh Test Procedure: Trigger RDKC Build and test, tested on Local builld PC, Test on jenkins Risks: Med
Priority: P0

[CI][AUTO] Xw4 Version retrieved are different after CDL - RDKLOGGER is not ON in xCAM2 and xCAM3

---

src/rtmessage/rtLog.c

RDKC-12563: Continuous flooding seen in various logs from RTMESSAGE and RBUS module 
RDKB-45841 : Log files are empty after 5 min uptime after upgrade/reboot/FR
Reason for change: Change for RDK logger for we used the rtLogLevel_t as is to pass to RDKLogger for rdk_LogLevel which is wrong,  RT_LOG_DEBUG is 0 where as RDK_LOG_FATAL is also 0. So this lead all the debug to be printed as FATAL and similarly, all the INFO to be printed as ERROR. Test Procedure: Trigger RDKC and RDKB Build and test by flashing respective images and verify Logs of on Device. Risks: Med
Priority: P0

RDKC-12563,RDKB-45841 - Continuous flooding seen in various logs from RBUS module

---

utils/rbuscli/rbuscli.c

Reason for change: rbuscli set failing when commit field is passed. 
Test Procedure: execute command set Device.X_RDK_WanManager.CPEInterface.1.Wan.Name string wan0 false in rbuscli 
Risks: Low
Signed-off-by: Deepthi DEEPTHICHANDRASHEKAR_SHETTY@comcast.com

RDKB-44725: rbuscli set failing when commit field is passed

---

src/rbus/rbus.c
unittests/rbusApiNegTest.cpp

Reason for change: CcspBaseIf_informEndOfSession API returns failure with status 102 
Test Procedure: CcspBaseIf_informEndOfSession API should return success 
Risks: Low
Signed-off-by: Deepthi <DEEPTHICHANDRASHEKAR_SHETTY@comcast.com>

RDKB-45774:[TDK][AUTO][22Q4_SPRINT][CCSPCOMMON_MBUS]CcspBaseIf_informEndOfSession API returns failure with status 102

---

utils/rbuscli/rbuscli.c

RDKB-45878: RBUS cli utility doesn't have the provision to give the interval as argument
Reason for change: Added interval based subscription
Test Procedure: execute command "subint <event> <interval> in rbuscli
Risks: Low
Priority: P0
Signed-off-by: Netaji Panigrahi <Netaji_Panigrahi@comcast.com>

RBUS cli utility doesn't have the provision to given the interval as argument

---

include/rbus.h
sampleapps/consumer/rbusEventConsumer.c
sampleapps/consumer/rbusValueChangeConsumer.c
src/core/rbuscore.c
src/core/rbuscore.h
src/core/rbuscore_types.h
src/rbus/rbus.c
test/rbus/consumer/subscribeEx.c
test/rbus/consumer/valueChange.c
unittests/rbus_unit_test_event_client.cpp
unittests/rbus_unit_test_event_server.cpp
utils/rbuscli/rbuscli.c

Reason for change: Whenever subscribeEx is called with PublishOnSubscribe set(new element added to rbusEventSubscription_t structure), we will publish the initial value of the data model as soon as the subscription is sent. The data is sent in the below format
For property/event:
{"initialValue": data model value at time of subscription} 
Ex: {"initialValue": 123}
For Table:
{"numberOfEntries": row count, "path1": path1 name, "path2": path2 name, "path3":path3 name}
Ex: {"numberOfEntries": 3, "path1": "a.1", "path2": "a.2", "path3":"a.3"}
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR gururaja_erodesriranganramlingham@comcast.com

RDKB-44740 RDKB-44861 : RBUS Subscribe API to get Initial Value

---

src/core/rbuscore.c
src/rbus/rbus.c

Reason for change: Single outParams variable is used in the rbusMethodConsumer. Whenever rbusMethod_Invoke() is called with a method which doesn't exist in the provider side, then the outParam value is NULL. Which is getting dereferenced in rbusObject_fwrite() resulted in crash. Handled outParam in rbus when the rbuscore returns failure.
Risks: Medium
Priority: P1

RDKB-46238 : rbusMethodConsumer testapp crash

---

src/rtmessage/rtRoutingTree.c
src/rtmessage/rtRoutingTree.h
src/rtmessage/rtrouted.c

Reason for change: Revert "RDKB-45652: Can't find destination component for multiple parameters (rdkcentral#39)"
This reverts commit 6950243
Revert "if else alignment change for better readability (rdkcentral#34)" This reverts commit 449f1c7
Risks: Medium
Priority: P1

RDKB-45907: The routing logic change rbus is redefined

---

sampleapps/consumer/rbusOpenTelemetry.c
src/core/rbuscore.c

Reason for change: Fixed memory leak issue
Risks: Medium
Priority: P1

RDKB-44935 : [RBUS] Add TraceContext support for distributed tracing

---

sampleapps/consumer/rbusTableConsumer.c
sampleapps/provider/rbusEventProvider.c
src/core/rbuscore.c
src/rbus/rbus.c

Reason for change: Fixed the memory leak issue reported while testing with testapp
This also should fix the OneWifi memory leak as both the valgrind result points 
to the same location
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR gururaja_erodesriranganramlingham@comcast.com

RDKB-46420 RDKB-46368 : Memory leak on Testapp and OneWifi

---

src/rbus/rbus.c

RDKB-46268 Random segmentation fault occurring while running rbusTestConsumer app
Reason for change: Observed Segmentation fault when ran rbusTestConsumer app on Ubuntu 21.10. Test Procedure: Build rbus on Ubuntu 21.10, run rnusTestProvider and rbusTestConsumer -a with gdb and bt Risks: Med
Priority: P1

RDKB-46268 Random segmentation fault occurring while running rbusTestConsumer app

---

include/rbus.h
sampleapps/consumer/rbusIntervalConsumer.c
src/rbus/rbus_intervalsubscription.c
utils/rbuscli/rbuscli.c

RDKB-46586 : RBUS - Support for duration based subscription
Reason for change: Added support for passing duration while
subscribing in RBUS and rbuscli support.
Test Procedure: 
```
1. Run rbusIntervalProvider/rbusIntervalConsumer sample apps for both interval and duration support
2. run rbuscli -i in two different terminals
- [ Terminal 1] [Provider]
-> reg prop a.b.c 
-> set a.b.c int 29
- [ Terminal 2] [Consumer]
-> subint a.b.c 10 60 true
```                          
Risks: Medium
Priority: P1
Signed-off-by: Netaji Panigrahi <Netaji_Panigrahi@comcast.com>

RBUS - Support for duration based subscription

---

src/core/rbuscore.c

Reason for change: Fixed memory leak issue
Test Procedure: Test and verified with valgrind
Risks: Low

RDKB-46554: Memory leak in EventClientAPIs.rbus_subscribeToEventTimeout_test1

---

src/rbus/rbus_subscriptions.c

Reason for change: Implement provider side resubscribing of subscriptions of event with aliasName that are recovered if provider restarts due to crash 
Risks: Medium
Priority: P1

RDKB-46677: Provider Crashed with Active Subscription of event with aliasName is not publishing after restart

---

src/rtmessage/rtError.c
src/rtmessage/rtrouted.c
test/rbus/provider/rbusTestProvider.c

RDKB-46634 Rbus build warnings from src folder needs fix on Ubuntu-22.10 ver
Reason for change: three Build Warning (-Waddress) observed while compiling RBus files rtError.c rtrouted.c in src/ and rbusTestProvider.c in test/ folder on Ubuntu 22.10 Test Procedure: Build rbus on Ubuntu 21.10.
Risks: Med
Priority: P2

RDKB-46634 Rbus build warnings from src folder needs fix on Ubuntu-22.10

---

src/rbus/rbus_subscriptions.c

Revert "RDKB-46677: Provider Crashed with Active Subscription of event with aliasName is not publishing after restart"

---

src/core/rbuscore.c
src/rtmessage/rtrouted.c
utils/rbuscli/rbuscli.c

Reason for change: Fixed memory leak with rbus_discoverComponentDataElements, rbus_discoverObjectElements and rbus_discoverObjectsElements
Risks: Medium
Priority: P1

RDKCOM-3564 : Memory Leak with rbus_discoverComponentDataElements

---

src/rbus/rbus_config.c

Reason for change: Requesting sessionid by CcspBaseIf_requestSessionID is resulting in a crash 
Risks: Medium

Ensure to to have rbusConfig created for all the rbus APIs

---

src/rbus/rbus.c

Setting componentName of RbusHandle to NULL in rbus_close
Reason for change: RbusHandle pointer to componentName was not initialized to NULL in rbus_close function. And VERIFY_NULL check for same parameter was missing in rbus_regDataElements function
Test Procedure:
1.Load the test build in device
2.Connect few clients and perform 20 rounds of reboots.
3.Check Stacktrace if any crash is seen.
Risks: Medium
Priority: P1

Setting componentName of RbusHandle to NULL in rbus_close

---

src/core/rbuscore.c
unittests/rbus_unit_test_event_server.cpp
unittests/rbus_unit_test_server.cpp

RDKB-48378 : Must keep one active connection to Daemon until the last handle is closed
Reason for change: When a rbus_open component with same name is closed, rbus_closeBrokerConnection should not destroy any exiting active component session Test Procedure: 1)Run rtrouted;Run rbusSampleProvider and verify get and set of its components via rbuscli;
2)Run rbus_gtest and verify all Test passed in previous commit are passing with change
Risks: Medium
Priority: P1

RDKB-48378 : Must keep one active connection to Daemon until the last handle is closed

---

test/rbus/consumer/rbusTestConsumer.c

*RDKB-48890 Addressing Unit test work flow on Github Rdkcentral Rbus
Reason for change: Github unittest workflow is not capturing failure count of rbusTestConsumer
Test Procedure: Trigger and verify Unittest work flow on rdkcentral rbus github
Risks: Medium
Priority: P1

RDKB-48890 Addressing Unit test work flow on Github Rdkcentral Rbus

---

src/rbus/rbus_subscriptions.c

RDKB-48936 [23Q2_Sprint] Events Test Cases are Failing in rbusTestConsumer
Reason for change: Reverting RDKB-46677 as 32 test cases of rbusTestConsumer was failing on Github unittest
Test Procedure: Verify rbusTestConsumer on VM and Unittest work flow on rdkcentral rbus github
Risks: Medium
Priority: P1

RDKB-48936 [23Q2_Sprint] Events Test Cases are Failing in rbusTestConsumer

---

src/rtmessage/rtConnection.c

Reason for change: Avoid using script/system commands using system functions
Test Procedure:    Tested and verified
Risks:             Medium
Priority:          P1

RDKC-13696: RBUS: Avoid using script/system commands using system functions

---

src/rtmessage/rtEncoder.c
src/rtmessage/rtMessageHeader.c

Reason for change: values are not encoded as uint values, but are being encoded as signed integers.
Risks: Medium
Priority: P1

RDKB-50100: Encoding, an rtMessage structure types are incorrect

---

utils/rbuscli/rbuscli.c

rbuscli [-g parameter ]   /* Get the value of parameter */
`./rbuscli -g a.b.c`
rbuscli [-s parameter type value ]  /* Set the value of parameter */
` ./rbuscli -s a.b.c int 29`

Add support for rbuscli with -g and -s options

---

utils/rbuscli/rbuscli.c

Removed using of Carriage Return (\r) from the rbuscli -g option printf function.

Removed Carriage Return (\r) from the output of rbuscli -g option

---

utils/rbuscli/rbuscli.c

Not accept wildcard query for rbuscli -g command input

Remove wildcard support for rbuscli -g option

---

sampleapps/consumer/rbusThreadConsumer.c

Reason for change: For fixing the testapp build error while building with jenkins
Risks: Medium
Priority: P1

RDKB-51121 : Onewifi crash observed with function strlen, rtLogPrintf

---

include/rbus.h
src/rbus/rbus.c
test/rbus/consumer/subscribe.c

new method to support consumer to find whether they have active subscription already or not for the given DML with subscription structure.
Test Procedure: verified with ./rbusTestProvider & rbusTestConsumer

RDKB-51177:RBUS- API to find event subscription

---

src/rbus/rbus.c

Reason for change: Handled UnSubscription of DML when provider is not running.
If an event's unsubscription fails because a provider cannot be discovered, the subscription node is marked as dirty, and it will be resolved when the provider is active and publishes the event.
Test Procedure: 
```
In terminal 1: Start rtrouted,
In terminal 2: run the ./rbusEventProvider.
In terminal 3: run rbuscli -i
Test steps:
1. Subscribe DML "Device.Provider1.Param1"
sub Device.Provider1.Param1
2. In terminal 2 : Kill ./rbusEventProvider
3. In terminal 3: unsub Device.Provider1.Param1
4. In terminal 2, run the ./rbusEventProvider.
5. In terminal 3: Verify "Device.Provider1.Param1" unsubscription will be success
```

RDKB-50101 : RBUS Event Producer can have multiple instances of the same Subscriber

---

sampleapps/CMakeLists.txt
sampleapps/provider/rbusRawDataProvider.c
src/rbus/rbus.c

Reason for change: The subscriptions list on the consumer side is not mutex protected. As a result, when some component subscribes/unsubscribes the event, it affects the subscription list at the same time.
Test Procedure: Verified with TestProvider & TestConsumer

RDKB-51301 : RBUS - Add mutex-protected to the Consumer side's subscriptions list

---

src/rbus/rbus.c

Reason for change: Reading 'inParms' in the _method_callback_handler function without adding 'inParms' in the request message in rbusMethod_InvokeInternal() results in an error.
The 'hasInParam' variable was added to find out whether a request message has inParams or not.
Risks: Low
Priority: P1

Observing provider side erro while using 'method_noargs' rbuscli command

---

src/rbus/rbus.c
src/rbus/rbus_handle.h
src/rbus/rbus_intervalsubscription.c

Reason for change: Used common mutex for both Provider & Consumer side subscriptions lists, so added separate mutex variable for Provider & Consumer.

RDKB-52005:RBUS - Use separate mutex for Provider & Consumer side lists.

---

src/rbus/rbus.c

Reason for change: In rbusEvent_SubscribeWithRetries, using subInternal is not mutex protected. AS a result, when unsubscription occur at the same time and it removed subInternal from the List leads to crash. Using subInternal under mutex protection to avoid crash.

RDKB-51891:Observed "OneWifi" crash with with Fingerprint:61377904

---

src/rbus/rbus.c
src/rbus/rbus_subscriptions.c
src/rtmessage/rtrouted.c

Reason for change: While recovering from a crash, the provider is unaware of a valid rbus_open connection of consumer, so it lead to multiple instances of the same Subscriber. Before loading old subscriptions from the cache file, a "/tmp/.rbus/ConsumerPID_ComponentID" file existence check is now performed.

RDKB-50101:RBUS Event Producer can have multiple instances of the same Subscriber

---

src/core/rbuscore.c
src/rbus/rbus.c
src/rbus/rbus_asyncsubscribe.c
src/rbus/rbus_config.c
src/rbus/rbus_element.c
src/rbus/rbus_handle.c
src/rbus/rbus_intervalsubscription.c
src/rbus/rbus_subscriptions.c
src/rbus/rbus_tokenchain.c
src/rbus/rbus_value.c
src/rbus/rbus_valuechange.c

Reason for change: Removing unwanted function names from logging messages

RBUS-Update logging messages

---

src/rtmessage/rtrouted.c

Reason for change: The provider is unable to access the subscribers' component ID file due to the restricted access permission of the '/tmp/.rbus' directory. Modified directory permission to access it.

LTE-2173: [XLE][23Q4] XLE and XB are in split brain mode always

---

.github/workflows/unit_tests.yml
test/rbus/multiRbusOpenMethodConsumer/multiRbusOpenMethodConsumer.c

RDKB-51761 Test scenario to cover multiple rbus_open() call
Reason for change: Fixing intermittent crash in multiRbusOpenMethodConsumer
Test Procedure: Start rtrouted and ./rbus_test.sh or verify .github/workflows/unit_tests.yml 
Risks: Medium
Priority: P1

 RDKB-51761 : Test Suite Enhancements

---

src/rtmessage/rtrouted.c

Reason for change: Because of a permissions issue with the /tmp/.rbus directory, the provider is unable to access the subscribers' component ID file. 

RDKB-52350:Gateway Manager gets stuck & XLE fails to do GFO or Restore

---

src/rtmessage/rtHashMap.c

LTE-2047 [AUTO][Release][6.7]Observed cellularmanager crash with signature 85788042 and reason as SIGSEGV /SEGV_MAPERR after 3 days of uptime
Reason for change: Observed cellularmanager crash with signature 85788042 and reason as SIGSEGV /SEGV_MAPERR after 3 days of uptime Test Procedure: Testing mentioned in Jira description
1)XLE is with flashed with 6.7p1s6 release build
2)XB is flashed with 6.2p26s1 release build
3)XLE is an extender connected to XB via wifiBH
4)2 clients connected to the setup
Risks: Low
Priority: P1

LTE-2047 [AUTO][Release][6.7]Observed cellularmanager crash with signature 85788042 and reason as SIGSEGV /SEGV_MAPERR after 3 days of uptime

---

src/core/rbuscore.c
src/core/rbuscore.h
src/rbus/rbus_message.c
src/rtmessage/CMakeLists.txt
src/rtmessage/rtConnection.c
src/rtmessage/rtConnection.h

Reason for change: Added new API for add and remove listener which will work based on the subscription ID. The existing API will remain to support the RDKC build. Also addressed the compile time issue faced for ccspcommonlibrary
Test Procedure: Build and verified
Risks: Low
Priority: P1
Signed-off-by: Gururaaja ESR <Gururaja_ErodeSriranganRamlingham@comcast.com>

RDKB-51547 : [On rbusDirect] Implementation of RBUS Publish API to send Raw Data

---

src/core/rbuscore.c
src/core/rbuscore.h
src/rbus/rbus_subscriptions.c

Reason for change: Fixed the ssh failure issue reported in CI testing.
Test Procedure: Build and verified
Risks: Low
Priority: P1
Signed-off-by: Gururaaja ESR <Gururaja_ErodeSriranganRamlingham@comcast.com>

RDKB-51547 - [On rbusDirect] Implementation of RBUS Publish API to send Raw Data

---

.github/workflows/unit_tests.yml
unittests/main.cpp
unittests/rbusApiNegTest.cpp
unittests/rbusConsumer.cpp
unittests/rbus_unit_test_server.cpp

Reason for change: Fix unittest cases failure
Test Procedure: Run rtrouted, rbus_session_mgr and rbus_gtest.bin
Risks: Medium
Priority: P1

RDKB-53701: Fix unittest failure in rbus_gtest binary

---

unittests/rbus_unit_test_server.cpp

Reason for change: run rbus_gtest.bin on device
Risks: Medium
Priority: P1

RDKB-54115: Addressing segmentation fault in rbus_gtest binary

---

CMakeLists.txt

Reason for change: Add AddressSanitizer as a CMake build option for the rbus code
Test Procedure: Test and verified.
Risks: Medium
Priority: P1

RDKB-54346: Add AddressSanitizer as a CMake build option for the rbus code

---

src/rbus/rbus_value.c
test/rbus/consumer/valueAPI.c
unittests/rbusValueTest.cpp

Reason for change: rbusValue_ToString functions converts in parameter Boolean type value into "true/false" strings

RDKB-54519: RBUS - rbusValue_ToString converts parameter boolean value into "true/false" strings

---

src/core/rbuscore.c
src/rbus/CMakeLists.txt
src/rbus/rbus.c
src/rbus/rbus_asyncsubscribe.c
test/rbus/consumer/methods.c
unittests/CMakeLists.txt
unittests/rbusProvider.cpp

Reason for change: Fix Memory leak in rbus code.
Test Procedure: Test and verified with rbuscli and testapp.
Risks: Medium
Priority: P1

RDKB-54362: Fix Memory Leak in sampleApps, testsuites and gtest cases

---

src/core/rbuscore.c
src/rbus/rbus.c
src/rbus/rbus_asyncsubscribe.c
test/rbus/consumer/methods.c
unittests/rbusApiNegTest.cpp
unittests/rbusFunctionalityTest.cpp
unittests/rbus_unit_stresstest_server.cpp
unittests/rbus_unit_test_client.cpp
unittests/rbus_unit_test_event_client.cpp
unittests/rbus_unit_test_multiple_objects.cpp

Reason for change: When an object not found error originates from rtrouted,
rbuscore returs error code RBUSCORE_ERROR_ENTRY_NOT_FOUND
instead of RBUSCORE_ERROR_DESTINATION_UNREACHABLE.
Signed-off-by: Netaji Panigrahi <Netaji_Panigrahi@comcast.com>

Fix: Modifying Error Codes in RBUS Core

---

rdk_build.sh

The location of prebuilt breakpad binaries has been changed from utility repo to build framework repo under opensource prebuilts. Updating the same with this code change.

RDKC-14860: Updating the path for prebuilt breakpad binaries

---

src/core/rbuscore.c

Reason for change: Fix Memory leak in rbus code.
Test Procedure: Test and verified with rbuscli.
Risks: Medium
Priority: P1
Signed-off-by: Prabhudas Gannavarapu <prabhudas_gannavarapu@comcast.com>

REFPLTB-3035: Memory leak in rbus "rbus_discoverRegisteredComponents"

---

src/rbus/rbus.c

Reason for change: The crash occurred due to an invalid memory 
access. The rbusProperty_Release() function is to release local 
variables that have previously been freed. 
To resolve the problem, the local variable was initialized with "NULL".         

RDKB-55966: "rbuscli get Device.WiFi." failed with Segmentation fault

---

src/rtmessage/rtConnection.c

Reason for change: select system call times out (after 60 seconds) and then enters a 5-second sleep. During this sleep period, rtrouted sends the provider details to telemetry2_0.
Test Procedure: none
Risks: Medium
Priority: P1
Signed-off-by: garumu177 <Gokulraj_Arumugam@comcast.com>

RDKC-15260 : XCAM2 devices failing to fetch the TR181 parameter value of Device.DeviceInfo.X_RDKCENTRAL-COM_MAC

---

src/rbus/rbus_config.c

void compiler warnings
Test Procedure: Sanity.
Risks: None.

RDKBDEV-2826: check fread() return values to avoid compiler warnings

---

sampleapps/consumer/rbusOpenTelemetry.c

avoid compiler warnings
Test Procedure: Sanity.
Risks: None.

RDKBDEV-2827: check scanf() return values to avoid compiler warnings

---

src/core/rbuscore.c

1,024 bytes in 1 blocks are definitely lost in loss record 318 of 350 malloc (vg_replace_malloc.c:309)
rbus_getOpenTelemetryContextFromThreadLocal (rbuscore.c:2276) rbus_getOpenTelemetryContextFromThreadLocal (rbuscore.c:2269) rbus_getOpenTelemetryContext (rbuscore.c:2290)
rbus_invokeRemoteMethod (rbuscore.c:1064)
Test Procedure: Sanity.
Risks: None.

RDKBDEV-2830: fix memory leak in rbus_invokeRemoteMethod

---

src/rbus/rbus.c

fix GetParameterAttributes RPC on root object returns fault code 9002 ( OFW-4277 )
Test Procedure: Sanity.
Risks: None.
Signed-off-by: anil shetty <adshetty@libertyglobal.com>

RDKBDEV-2829: fix GetParameterAttributes RPC

---

include/rbus.h
src/rbus/rbus.c
utils/rbuscli/rbuscli.c

Reason for change: Added support for the 'METHOD_COMMIT' functionality

Implementation of RBUS Publish API to support the setCommit functionality

---

unittests/rbusProvider.cpp

Reason for change: Fix compilation error in unittest code. In C, a void* can point to any data type, which means the compiler won't enforce type checking for assignments to void*. So only made changes in .cpp file.
Test Procedure: Test and verified.
Risks: Medium
Priority: P1

RDKB-57601: Fix compilation error in unittest code

---

src/rbus/rbus.c

Reason for change: Fixed errors when ran valgrind for rbusTestConsumer -a
Test Procedure: run rbusTestConsumer with valgrind
Risks: None.

RDKB-57423: Observed errors when ran valgrind for rbusTestConsumer -a

---

src/core/rbuscore_message.c

fix error message typo: rbuscore_message.c:204
rbusMessage_GetBytes unexpected date type 5 Update date -> data Test Procecedure: Sanity.
Risks: None.
Signed-off-by: mkamat <mkamat@libertyglobal.com>

RDKCOM-5110 RDKBDEV-2975: fix error message typo

---

src/rbus/rbus_element.c

Reason for change: Added proper locking and the missing unlock at early exit conditions where it was previously missing.
Signed-off-by: Netaji Panigrahi [Netaji_Panigrahi@comcast.com](mailto:Netaji_Panigrahi@comcast.com)

Add proper LOCK & missing UNLOCK at early exit for rbus_element

---

src/rtmessage/rtThreadPool.c

Reason for change: Added missing unlock at early exit conditions where it was previously missing.
Signed-off-by: Netaji Panigrahi [Netaji_Panigrahi@comcast.com](mailto:Netaji_Panigrahi@comcast.com)

add missing mutex unlock at early exit rtThreadPool

---

src/rbus/rbus.c
test/rbus/CMakeLists.txt
test/rbus/multiRbusOpenEventConsumer/multiRbusOpenEventConsumer.c
test/rbus/multiRbusOpenEventProvider/multiRbusOpenEventProvider.c

Reason for change: The subscriberID sent while publishing the initial value is invalid and that leads the subscriber side of the middleware to ignore the received message itself and causes no event received at the consumer/subscriber
Test Procedure: As per RDKB-57964
Risks: Low

RDKB-57964: Delay in getting the ipv6 after WanManager Restart

---

src/rbus/rbus_value.c

Reason for change: Multiple components are crashing after bootup where it is trying to dereference the NULL pointer.
Priority: P0

RDKB-59246: Multiple components are crashing in "rbusValue_SetFromString".

---

src/rbus/rbus.c

Reason for change: Stop calling rbus_discoverComponentName for single parameter in rbus_getExt and rbus_setMulti functions

RDKB-59378 : Prevent destination discovery in rbus_getExt and rbus_setMulti for single parameter

---

src/rbus/rbus.c

Reason for change: Fix Memory leak in _setMultiInternal function.

RDKB-59706 : fix memory leak in _setMultiInternal

---

src/rtmessage/rtConnection.c

The code changes in this PR were automatically generated by the Permanence AI coder and reviewed by @jweese and @fwph. `con` is dereferenced in order to set `last_reconnect_time`, but this happens before `con` is checked to be non-null. This change moves the assignment below the check.
Compare to https://github.com/rdkcentral/rbus/pull/252/ -- a similar issue in `rbus_value.c` was fixed by moving the dereference below the check.

rtmessage: repair NULL Pointer Dereference for rtConnection

---

src/rtmessage/rtConnection.c

The code changes in the PR were generated automatically by the Permanence AI Coder and reviewed by @jweese and @fwph. On line 368, `setsockopt` can fail, so this change checks its return value. Since the original code does not return early on failure, neither does this change, but it does log the error. Some minor trailing whitespace was also removed.

rtmessage: check return value of setsockopt

---

src/rtmessage/rtrouted.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph.
After the final iteration of this loop, `i` is zero and the loop terminates, and then `i` is decremented and underflows. In practice, this is not a problem since `i` is never used again, but it may be flagged by a static analyzer. This changes to a for loop that doesn't underflow.

rtmessage: fixup integer underflow for rtrouted

---

src/rbus/rbus_subscriptions.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. In the case of an early return where `subscriptions` is NULL, the current code leaks the newly-allocated token chain in `tokens`. It was meant to be assigned into `sub->tokens` later. Instead, on this early return, this change destroys the unused token chain.

rbus: fix TokenChain leak in rbus_subscriptions

---

unittests/CMakeLists.txt

Reason for change: Remove rbus_gtest patch from rbus recipe
Priority: P1
Risks: High

RDKEMW-5498: Remove rbus_gtest patch from rbus recipe

---

src/rtmessage/rtrouteBase.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese, @fwph, @eelenberg, and @josephhackman. This adds an explicit null termination to `new_header.topic` to cover the case where the call to `strncpy` could hit its limit. It also changes `new_header.topic_length` to use the true copied length of the string, instead of the length of the source string, which could have been truncated.

rtmessage: fixup null termination in rtrouteBase L524

---

src/rtmessage/rtrouteBase.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. Add explicit null termination for `reply` and `reply_topic` to handle the case where `strncpy` could hit its limit and fail to null-terminate.

rtmessage: fixup null termination in rtRouteBase L188,189

---

src/rtmessage/rtrouted.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @eelenberg. Near the top of this function, `response` is allocated via `rtMessage_Create`. When allocation succeeds, the next line immediately attempts to get `expression`. When `expression` is valid, `response` is freed via `rtMessage_Release` at the end of the large `if` block. However, in the case that `response` is created but `expression` is invalid, there is no `else` block and `rtMessage_Release` is never called. This change adds the appropriate `else` block.

rtmessage: fixup potential leak in DiscoverObjectElements

---

src/rtmessage/rtrouteBase.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @eelenberg. `setsockopt` can fail, so this change checks the return value and logs a warning message on failure.

rtmessage: check return values of setsockopt

---

src/rbus/rbus_object.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. Here, `pobject` is passed directly to `rbusObject_Init` to hold its result but `pobject` is not modified inside that call. Therefore if it were null, the dereference `(*pobject)->type` would dereference a NULL pointer.

rbus_object: fixup potential leak in InitMultiInstance

---

.github/workflows/address-sanitizer.yml
.github/workflows/unit_tests.yml
.github/workflows/valgrind-test.yml
src/rbus/rbus.c

- The rbus library maintains list of active subscription that exist for any given DML.
- The rbus library uses mutex protection to access this list while adding, removing and while publishing.
- The flow in rbus library is, it locks the mutex when any consumer calls Subscribe/Unsubscribe and also informs the provider about the action if callback registered and adds to the list then unlocks the mutex.
- It is absolutely necessary to lock the mutex before we add/remove from the list but its not necessary to lock before notifying the provider about the action. Test Procedure: Verify Eventing
Risks: Medium

RDKB-60555 : Move the subscription mutex after notify

---

src/core/rbuscore.c

The changes in this PR were generated automatically by the Permanence AI Coder and reviewed by @jweese and @fwph. This change checks the return value of the `remove` call, and adds a log message on error.

core: check return value of remove

---

src/core/rbuscore.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. The assignment to `obj` here is immediately and unconditionally overwritten by the result of the call to `rtVector_Find` just below.

core: fix unused variable assignment

---

src/core/rbuscore.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. The call to `remove` can fail, so this change checks its return value and logs an error message on failure. Compare to #273.

core: check return value of cache file removal

---

src/rbus/rbus.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. A race condition may exist since the code checks that `handle->eventSubs` is valid before it acquires the lock using its macro. Since the thread may wait to acquire a lock, a separate thread could have held the lock and called `rtVectorDestroy` between the time this thread checked it and the time this thread acquired the lock. This change moves the scope of the held lock outward slightly so that it covers both the checking of the vector and the later free and destruction operations.

rbus_close: resolve potential race condition on eventSubs

---

src/core/rbuscore.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. `ret` has an initial value of `RBUSCORE_SUCCESS` and is only reassigned in the memory allocation failures just above. In each case (either the `else` branch at L1944 or the `break` out of the loop ending at L1942), control flow immediately continues to this line overwriting `ret` with `RBUSCORE_SUCCESS` again, making those assignments useless. (In the case of no errors, the initial value of `RBUSCORE_SUCCESS` is correct anyway.) This change removes the unneeded assignment to correctly return the assigned error values.

core: fixup error code assignment in discoverWildcardDestinations

---

src/core/rbuscore.c

The code changes in this PR were automatically generated by the Permanence AI Coder and reviewed by @jweese and @fwph. `ret` has an initial value of `RBUSCORE_SUCCESS` and is only reassigned in the memory allocation failures just above. In each case (either the `else` branch at L2294 or the `break` out of the loop ending at L2292), control flow immediately continues to this line overwriting `ret` with `RBUSCORE_SUCCESS` again, making those assignments useless. (In the case of no errors, the initial value of `RBUSCORE_SUCCESS` is correct anyway.) This change removes the unneeded assignment to correctly return the assigned error values.

core: fixup error code assignment in discoverRegisteredComponents
