- include/readme
- src/core/CMakeLists.txt
- src/rbus/CMakeLists.txt
- src/rtmessage/CMakeLists.txt
- unittests/rbus_unit_test_client.cpp
RDKB-44953 : Install header files in given PREFIX path
> Install header files in given PREFIX path

- .github/workflows/build.yml
Reason for change: Github workflow for rbus build
Signed-off-by: Netaji Panigrahi <Netaji_Panigrahi@comcast.com>
> Workflow to run the build for every check-in

- src/rtmessage/CMakeLists.txt
- src/session_manager/CMakeLists.txt
- utils/codegen/ccsp_style_generator/sampleapp/build.sh
- utils/codegen/ccsp_style_generator/scripts/rbus_code_generator_ccsp_style.sh
RDKB-44613: RDKB - Use RBUS from RDKCentral github
Reason for change: Updating Karuna's change in rtmessage CMakelists.txt, and other changes for solving some Rbus dependency errors for bitbake comcast-broadband-dev-image. Test Procedure: making changes on TECHNICOLORXB7 and checking "bitbake f -C compile rbus" an check is rbus is downloaded to work/ directory and all required lib and include files are installed (right now with INSANE_SKIP). The test full build "bitbake comcast-broadband-dev-image" and resolving component dependencies with Rbus Risks: Low
Priority: P1
Change-Id: I23af02926c84eb9b1aa8400deb2f7161738fa00f
> RDKB - Use RBUS from RDKCentral github

- include/rbus_object.h
- include/rbus_value.h
- unittests/rbusObjectTest.cpp
- unittests/rbusPropertyTest.cpp
- unittests/rbusValueTest.cpp
Reason for change: Increase Code coverage percentage for RBUS Test Procedure: Run rbusCodeCoverageUI
Risks: Low
Signed-off-by: Deepthi <DEEPTHICHANDRASHEKAR_SHETTY@comcast.com>
> Increase Code coverage percentage for RBUS

- src/rtmessage/rtConnection.c
Reason for change: Changes to fix the telemetry crash issue faced with RTT 0 sec issue fix
Risks: Medium
Priority: P1
> RDKB-44765 - Changes to fix the crash issue

- cmake/CodeCoverage.cmake
- src/session_manager/session_manager.c
- unittests/rbus_unit_test_client.cpp
- unittests/rbus_unit_test_event_client.cpp
RDKB-45123: Add unit test to ensure better testing and code coverage
> Add unit test to ensure better testing and code coverage

- CMakeLists.txt
> Release 2.0.2

- include/rbus.h
- sampleapps/consumer/rbusEventConsumer.c
- sampleapps/consumer/rbusValueChangeConsumer.c
- src/core/rbuscore.c
- src/core/rbuscore.h
- src/core/rbuscore_types.h
- src/rbus/rbus.c
- test/rbus/consumer/subscribeEx.c
- test/rbus/consumer/valueChange.c
- unittests/rbus_unit_test_event_client.cpp
- unittests/rbus_unit_test_event_server.cpp
- utils/rbuscli/rbuscli.c
> Revert "RDKB-44740 RDKB-44861 : RBUS Subscribe API to get Initial Value"

- include/rbus.h
- sampleapps/consumer/rbusEventConsumer.c
- sampleapps/consumer/rbusValueChangeConsumer.c
- src/core/rbuscore.c
- src/core/rbuscore.h
- src/core/rbuscore_types.h
- src/rbus/rbus.c
- test/rbus/consumer/subscribeEx.c
- test/rbus/consumer/valueChange.c
- unittests/rbus_unit_test_event_client.cpp
- unittests/rbus_unit_test_event_server.cpp
- utils/rbuscli/rbuscli.c
Reverts rdkcentral/rbus#63
To bring back the  rdkcentral/rbus#62
> Revert "Revert "RDKB-44740 RDKB-44861 : RBUS Subscribe API to get Initial Value""

- sampleapps/consumer/rbusEventConsumer.c
- sampleapps/consumer/rbusTableConsumer.c
- sampleapps/provider/rbusEventProvider.c
- sampleapps/provider/rbusTableProvider.c
- src/core/rbuscore.c
- src/core/rbuscore_types.h
Reason for change: Fixed the gtest issue reported by tester. Also added new test cases in rbusEventConsumer and rbusTableConsumer to test the subscribe with initial value
Risks: Medium
Priority: P1
Signed-off-by: Gururaaja ESR gururaja_erodesriranganramlingham@comcast.com
> RDKB-44740 RDKB-44861 : RBUS Subscribe API to get Initial Value

- src/core/rbuscore.c
Clear the context upon receiving
> Clear the context upon receiving

- src/rbus/rbus.c
- src/rbus/rbus_subscriptions.c
- src/rbus/rbus_subscriptions.h
- src/rbus/rbus_tokenchain.c
Reason for change: Implement provider side resubscribing of subscriptions that are recovered if provider restarts due to crash 
Risks: Medium
Priority: P1
> RDKB-45942: Active Subscription is not publishing after Provider crash recovery

- src/rbus/rbus.c
- utils/rbuscli/rbuscli.c
Reason for change: Fixed the crash issue reported with initial value subscription
Risks: Medium
Priority: P1
> RDKB-44740 RDKB-44861 : RBUS Subscribe API to get Initial value 

- sampleapps/consumer/rbusIntervalConsumer.c
- src/rbus/rbus.c
- src/rbus/rbus_intervalsubscription.c
- utils/rbuscli/rbuscli.c
RDKB-46586: RBUS - Support for duration based subscription
Handling duration complete event type while receiving event
> Added duration complete event type while receiving event

- sampleapps/CMakeLists.txt
- sampleapps/consumer/sample_rbus_session_mgr.c
Reason for change: For testing functionality of rbusSession APIs 
Test Procedure: Execute command ./sample_rbus_session_mgr
Risks: Low
> RDKB-45777: Sample code for rbus_session_mgr

- src/rbus/rbus.c
Update Log Level for rbus_regDataElements() for success case.
> Update Log Level for rbus registration API

- src/rtmessage/rtConnection.c
> Revert "RDKB-47035 : Single thread approach for rbus"

- src/rbus/rbus.c
- src/rbus/rbus_handle.h
- src/rtmessage/rtAtomic.h
- src/rtmessage/rtFuture.c
- src/rtmessage/rtFuture.h
Libev changes to fix the review comments of PR94
> Libev changes to fix the review comments of PR94

- src/core/rbuscore.c
- src/rbus/rbus.c
- src/rbus/rbus_element.h
> Fixed the mutex variable

- src/core/rbuscore.c
- src/rbus/rbus.c
- src/rbus/rbus_element.c
- src/rbus/rbus_element.h
Fixed the Build Error with CLANG (XE2) and minor fixes
> Fixed the Build Error with CLANG (XE2) and minor fixes

- src/rtmessage/rtrouteBase.c
Updated access permission of the unix for the non-root clients
> Update access permission of the unix socket

- sampleapps/consumer/rbusOpenTelemetry.c
openTelemetry app to take input from user and set that as traceparent&tracestate
> openTelemetry sample app to take input from user 

- src/rbus/rbus.c
- src/rbus/rbus_subscriptions.c
RDKB-50778 [AUTO][Stable2/6.3]Observing "rbusSubscriptions_saveCache" logs flooding in telemetry2_0.txt.0
modifying a log level to DEBUG
> RDKB-50778 [AUTO][Stable2/6.3]Observing "rbusSubscriptions_saveCache" logs flooding in telemetry2_0.txt.0

- sampleapps/provider/rbusEventProvider.c
- sampleapps/provider/rbusValueChangeProvider.c
- src/rbus/rbus.c
- test/rbus/provider/rbusTestProvider.c
Reason for change: By default AutoPublish is set to false for ValueChange
Risks: Low
Priority: P1
> RDKB-51511: Turn Off AutoPublish feature for ValueChange

- src/rbus/rbus.c
- src/rbus/rbus_subscriptions.c
- src/rbus/rbus_subscriptions.h
> Consumer side use dirty subscription record for second time subscription

- src/rbus/rbus.c
Turn On AutoPublish feature by default
> Turn On AutoPublish feature by default

- src/rbus/rbus.c
Reason for change: The Disconnect Event Handler registration has been utilised in rbus_openDirect and removed from other places
> RDKB-51370: Use the Disconnect Event Handler for rbus direct connections

- src/core/rbuscore.c
- src/core/rbuscore.h
- src/rbus/rbus.c
- src/rbus/rbus_intervalsubscription.c
- src/rtmessage/rtrouteBase.c
- src/rtmessage/rtrouteBase.h
- unittests/rbus_unit_test_event_server.cpp
Reason for change: Removed topic created with subscriptionId for normal subscription and subscriptionId based topic is only created for rawdata direct mode subscription
Test Procedure: Test and verified with rbuscli and testapp Risks: High
Priority: P1
> RDKB-51547 : RawData Direct mode with subscription Id

- sampleapps/CMakeLists.txt
- sampleapps/consumer/rbusRawDataConsumer.c
- sampleapps/provider/rbusRawDataProvider.c
Reason for change: Added sample apps for raw data subscriptions testing
Test Procedure: Build and verified
Risks: Low
Priority: P1
Signed-off-by: Gururaaja ESR <Gururaja_ErodeSriranganRamlingham@comcast.com>
> RDKB-51547 - [On rbusDirect] Implementation of RBUS Publish API to send raw data

- .github/workflows/unit_tests.yml
Reason for change: Add CodeCoverage in Github workflow
Test Procedure: Check Codecoverage in github
Risks: Medium
Priority: P1
> RDKB-53752: Add CodeCoverage in Github workflow

- src/rbus/rbus.c
- utils/rbuscli/rbuscli.c
Reason for change: The getExt function returns a success error code if it is partially successful.
> RDKB-55856:DM is not working with CPE interface alias name

- sampleapps/consumer/rbusRawDataConsumer.c
- sampleapps/consumer/rbusSampleConsumer.c
- src/rbus/rbus_object.c
- src/rbus/rbus_property.c
- unittests/util.cpp
- utils/rbuscli/rbuscli.c
The sequence \n\r is not a valid line ending on either system. Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
> RDKBDEV-2828: A DOS line ending is \r\n. A Unix line ending is \n.

- src/rbus/rbus_subscriptions.c
- src/rtmessage/rtrouteBase.c
Reason for change: Handled error conditions and fixed memory leaks.
Signed-off-by: Netaji Panigrahi [Netaji_Panigrahi@comcast.com](mailto:Netaji_Panigrahi@comcast.com)
> Rbus fix memory leak

- include/rbus.h
- src/rbus/rbus.c
- unittests/rbusConsumer.cpp
- unittests/rbusFunctionalityTest.cpp
Reason for change: converted rbus_core errors to strings while logging them.
Signed-off-by: Netaji Panigrahi [[Netaji_Panigrahi@comcast.com](mailto:Netaji_Panigrahi@comcast.com)]
> RBUS-modify log messages & log level

- CMakeLists.txt
> Release of v2.3.0

- test/rbus/CMakeLists.txt
- test/rbus/rbusGetExtSetMulti/testSetMultiConsumer.c
- test/rbus/rbusGetExtSetMulti/testSetMultiProvider.c
Reason for change: test code to verify rollback failed case in _setMultiInternal and rbus_getExt with single parameter  
Test Procedure: Run valgrind
> Added test code for rbus_SetMulti rollback and rbus_getEXT functions

- .github/workflows/valgrind-test.yml
- memoryleak.sh
Added Valgrind yml file for memory leak check
> RDKB-59819 Run Valgrind in the RBUS Workflow

- CMakeLists.txt
> Release of v2.6.0

- include/rbus.h
- src/rbus/rbus.c
- src/rbus/rbus_value.c
RDKEMW-5996 : Handle potential memory leaks
> RDKEMW-5996 : Handle potential memory leaks

- .github/workflows/valgrind-test.yml
- CMakeLists.txt
- src/core/rbuscore.c
- src/rbus/rbus_subscriptions.c
- src/rtmessage/CMakeLists.txt
- src/rtmessage/rtString.c
- src/rtmessage/rtString.h
- src/rtmessage/rtrouted.c
Reason for change: Handle String Buffers and other corner cases of failure
Signed-off-by: RoseMary_Benny@comcast.com
> RDKMEW-5996 : Handle String Buffers and other corner cases of failure
